### ISSUE TITLE
骚操作啊！

### ISSUE THREAD

**Issue by swun90** [DA-southampton/NLP_ability#1]
广告到github，然后就贴一微信公众号！
不是不能推广自己，只是到开源世界推广自己的公众号，这吃相也太难看了

**Comment by DA-southampton** [comment]
**本来不想回复你，你这种不清楚事情真相上来就开嘲讽的行为真的很没品。**

但是也为了给后面的朋友看，在这里特意解释一下，回复你，我最开始是在知乎分享关于这个Transformer的答案合集，想让大家直接跳转到公众号下载，但是被知乎认定垃圾广告营销，禁言一天，所以无奈之下，只能选择了这个折中的行为。

我有没有想增长粉丝的心理？有。这种心理丢人吗，难看吗？我觉得不丢人，不难看。为什么？因为是我的东西，我有权决定如何分享，而且我没有并没有违背github的相关规定。

至于你说的，“在开源世界推广自己公众号，吃相太难看”。那么我想请问你，在哪里推广自己才可以。你这个“开源世界”四个字可以换成任何一个名词，比如“论坛/知乎...”。

在你心里github是一个技术圣地，不应该有这些东西。看你的时间线已经在github很多年了，那么我想问你，github开了sponsor请问你知道吗？你觉得这个吃相难看吗？

我牺牲我自己的时间和精力，写出来的东西，分享给大家，希望通过这种方式获得大家的关注，这就是吃相难看了？

你说我“然后就贴一微信公众号”。请问什么叫做“就”？？我在github慢慢的更新着文章，每次行为都可以查到，有的更新时间是在凌晨之后，比如我现在是在凌晨四点在回复你，这就是你说的这句话中的“就”的含义吗？我更新的东西你是看不到还是说你根本就不想看到。

我理解你的心情，你可能是从知乎看到我的文章，以为点开就是文章合集下载链接，突然看到是我的github页面，有点气急败坏，所以想发泄一通。可是你知道事情的真相吗？

就像我开头说的，请不要在不清楚事情真相的时候轻易的下结论，真的很没品，没有人会尊重你这种行为。我用我自己的勤劳奋斗获取东西，我不觉得丢人。

如果说github有规定说，不允许我这种贴公众号的规定，那么我遵守，我可以删掉或者看换一个地方去分享。

我觉得你没有权利，没有这个责任，也没有这个能力，去替github做出规定，去肆意嘲讽一些没有违反规定的内容，去驱除那些想要在在github上面分享自己的东西的人，不论他是一个菜鸟还是一个大佬还是其他。

**Comment by nieallen** [comment]
> 广告到github，然后就贴一微信公众号！
> 不是不能推广自己，只是到开源世界推广自己的公众号，这吃相也太难看了

你他妈，人家宣传个自己公众号吃你家大米了？再说了更多的人关注他，作者分享知识效率的就越高，有啥不好。你这种人直接骂就行，讲啥玩意道理你也是杠
