### ISSUE TITLE
Error: invalid path

### ISSUE THREAD

**Issue by gritjz** [DA-southampton/NLP_ability#4]
'深度学习自然语言处理/其他/20201210一周|技术问题答疑汇总.md' 

这个文件名字中有 " | ", 不符合git规范, 麻烦修改一下名字, 否则不能clone, 谢谢

**Comment by DA-southampton** [comment]
第一次碰到这种~~我改了名字，你试试现在可以不

**Comment by zhanchao019** [comment]
我都忘了QAQ 我之前这是在干啥来着

**Comment by gritjz** [comment]
> 第一次碰到这种~~我改了名字，你试试现在可以不

可以了，Thanks
